const exampleDesign = `module counter(input wire clk, input wire rst, output reg [3:0] count);
  always @(posedge clk) begin
    if (rst) count <= 4'd0;
    else count <= count + 1'b1;
  end
endmodule`;
const exampleTb = `\`timescale 1ns/1ps
module counter_tb;
  reg clk = 0, rst = 1;
  wire [3:0] count;
  counter dut(.clk(clk), .rst(rst), .count(count));
  always #5 clk = ~clk;
  initial begin
    $dumpfile("wave.vcd"); $dumpvars(0, counter_tb);
    #12 rst = 0; #50 $finish;
  end
endmodule`;
const state = { experiments: [], report: {}, radix: 'hex', pasteTarget: null };
const $ = (selector) => document.querySelector(selector);
const text = (selector) => $(selector)?.value || '';
function reportNumberText(value) { const map = { '1': '一', '2': '二', '3': '三', '4': '四', '5': '五', '6': '六', '7': '七', '8': '八', '9': '九', '10': '十' }; return map[String(value).trim()] || String(value).trim() || '一'; }
const escapeHtml = (value) => String(value ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const escapeTex = (value) => String(value ?? '').replace(/([\\{}$&#%_])/g, '\\$1').replace(/\^/g, '\\textasciicircum{}').replace(/~/g, '\\textasciitilde{}');

const stepLabels = ['编写 Verilog', '编写约束文件', '综合 / 实现', '仿真验证'];
function newExperiment() { return { title: '', principle: '', steps: '', analysis: '', design: '', testbench: '', designTop: '', simTop: '', images: [null, null, null, null], result: null }; }
function showToast(message) { const el = $('#toast'); el.textContent = message; el.classList.add('show'); clearTimeout(showToast.timer); showToast.timer = setTimeout(() => el.classList.remove('show'), 2400); }
function inferTop(code, fallback) { const modules = [...String(code).matchAll(/\bmodule\s+([A-Za-z_$][\w$]*)\b/g)].map((match) => match[1]); return modules.find((name) => /tb|testbench/i.test(name)) || modules[0] || fallback; }
function updateReportState() { state.report = { number: text('#reportNumber'), title: `实验${reportNumberText(text('#reportNumber'))}：${text('#reportName') || '未命名实验'}`, course: text('#courseName'), name: text('#studentName'), className: text('#studentClass'), id: text('#studentId'), email: text('#studentEmail'), date: text('#reportDate'), environment: text('#environment'), purpose: text('#purpose'), principle: text('#principle'), problems: text('#problems'), summary: text('#summary'), reflection: text('#reflection') }; $('#heroTitle').textContent = state.report.title; $('#titleExample').textContent = state.report.title; renderLatex(); }
function formatValue(value) { const raw = String(value ?? 'x').toLowerCase(); if (!/^[01]+$/.test(raw) || raw.length <= 1) return raw; if (state.radix === 'hex') return parseInt(raw, 2).toString(16).toUpperCase(); if (state.radix === 'dec') return String(parseInt(raw, 2)); return raw; }
function resultTableHtml(result) { const rows = result?.tests?.length ? result.tests : []; const names = Object.keys(rows.find((row) => row.values)?.values || {}); if (!rows.length) return '<div class="empty-result">仿真后将在这里生成真值表</div>'; return `<table><thead><tr><th>#</th><th>时间</th>${names.map((name) => `<th>${escapeHtml(name)}</th>`).join('')}<th>状态</th></tr></thead><tbody>${rows.map((row, index) => `<tr><td>${index + 1}</td><td>${escapeHtml(row.time)}</td>${names.map((name) => `<td>${escapeHtml(formatValue(row.values?.[name] ?? '-'))}</td>`).join('')}<td class="${row.pass ? 'pass' : 'fail'}">${row.pass ? 'PASS' : 'INFO'}</td></tr>`).join('')}</tbody></table>`; }
function renderExperiments() {
  const container = $('#experiments');
  const number = escapeHtml(state.report.number || '1');
  container.innerHTML = state.experiments.map((experiment, index) => `<article class="experiment-card card" data-index="${index}"><div class="experiment-head"><div><span class="experiment-number">${number}-${index + 1}</span><input class="experiment-title" value="${escapeHtml(experiment.title || `实验 ${state.report.number || '1'}-${index + 1}`)}"><p>独立代码、仿真、步骤截图和结果</p></div><div class="experiment-head-actions"><span class="badge ${experiment.result?.success ? 'success' : ''}">${experiment.result ? (experiment.result.success ? 'PASS' : 'FAIL') : '未运行'}</span><button class="danger" data-remove="${index}">删除</button></div></div><div class="experiment-fields"><label>实验思路 / 原理<textarea data-field="principle" rows="3">${escapeHtml(experiment.principle)}</textarea></label><label>实验步骤说明<textarea data-field="steps" rows="3" placeholder="例如：编写代码 → 综合 → 实现 → 仿真验证">${escapeHtml(experiment.steps)}</textarea></label><label>结果分析<textarea data-field="analysis" rows="3">${escapeHtml(experiment.analysis)}</textarea></label></div><div class="code-grid"><label>Verilog 设计代码<textarea class="code-input" data-field="design" spellcheck="false">${escapeHtml(experiment.design)}</textarea></label><label>激励 / Testbench<textarea class="code-input" data-field="testbench" spellcheck="false">${escapeHtml(experiment.testbench)}</textarea></label></div><div class="sim-controls"><label>设计顶层<input data-field="designTop" value="${escapeHtml(experiment.designTop || inferTop(experiment.design, ''))}"></label><label>仿真顶层<input data-field="simTop" value="${escapeHtml(experiment.simTop || inferTop(experiment.testbench, ''))}"></label><button class="ghost" data-example="${index}">载入示例</button><button class="run" data-run="${index}">▶ 仿真</button></div><div class="step-upload-grid">${stepLabels.map((label, stepIndex) => `<div class="step-upload" tabindex="0" contenteditable="true" role="button" data-paste-image="${index}:${stepIndex}"><span><b>图片 ${stepIndex + 1}</b>${label}</span><input type="file" accept="image/*" data-step-image="${index}:${stepIndex}">${experiment.images[stepIndex] ? `<img src="${experiment.images[stepIndex].data}" alt="${label}"><small>${escapeHtml(experiment.images[stepIndex].name)}　×</small>` : '<em>先点击此框，再按 Ctrl+V 粘贴截图；也可点击选择文件</em>'}</div>`).join('')}</div><div class="experiment-result"><div class="result-meta"><b>测试真值表</b><span>${experiment.result ? (experiment.result.tests?.length || 0) + ' 条记录' : '等待仿真'}</span></div><div class="truth-table">${resultTableHtml(experiment.result)}</div><pre class="log">${escapeHtml(experiment.result?.log || '仿真日志将在这里显示')}</pre></div></article>`).join(''); bindExperimentEvents(); }
function bindExperimentEvents() { document.querySelectorAll('.experiment-card').forEach((card) => { const index = Number(card.dataset.index); card.querySelector('.experiment-title')?.addEventListener('input', (event) => { state.experiments[index].title = event.target.value; renderLatex(); }); card.querySelectorAll('[data-field]').forEach((field) => field.addEventListener('input', () => { state.experiments[index][field.dataset.field] = field.value; renderLatex(); })); card.querySelector('[data-example]')?.addEventListener('click', () => { state.experiments[index].design = exampleDesign; state.experiments[index].testbench = exampleTb; state.experiments[index].designTop = 'counter'; state.experiments[index].simTop = 'counter_tb'; renderExperiments(); renderLatex(); showToast('示例代码已载入'); }); card.querySelector('[data-run]')?.addEventListener('click', () => runExperiment(index)); card.querySelector('[data-remove]')?.addEventListener('click', () => { state.experiments.splice(index, 1); renderExperiments(); renderLatex(); }); card.querySelectorAll('[data-step-image]').forEach((input) => input.addEventListener('change', (event) => { const [experimentIndex, stepIndex] = input.dataset.stepImage.split(':').map(Number); const file = event.target.files[0]; if (!file) return; saveStepImage(experimentIndex, stepIndex, file); })); card.querySelectorAll('[data-paste-image]').forEach((target) => { target.addEventListener('click', (event) => { if (event.target.tagName === 'INPUT') return; const [experimentIndex, stepIndex] = target.dataset.pasteImage.split(':').map(Number); state.pasteTarget = { experimentIndex, stepIndex }; document.querySelectorAll('.step-upload.active').forEach((item) => item.classList.remove('active')); target.classList.add('active'); target.focus(); showToast(`已选择图片 ${stepIndex + 1}，现在可以按 Ctrl+V 粘贴截图`); }); target.addEventListener('keydown', (event) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); target.click(); } }); }); }); }
function saveStepImage(experimentIndex, stepIndex, file) { if (!file) return; const reader = new FileReader(); reader.onload = () => { state.experiments[experimentIndex].images[stepIndex] = { name: file.name || `pasted-step-${stepIndex + 1}.png`, data: reader.result }; renderExperiments(); renderLatex(); }; reader.readAsDataURL(file); }
document.addEventListener('paste', (event) => { if (!state.pasteTarget) return; const item = [...(event.clipboardData?.items || [])].find((clipboardItem) => clipboardItem.type.startsWith('image/')); if (!item) return; event.preventDefault(); const { experimentIndex, stepIndex } = state.pasteTarget; saveStepImage(experimentIndex, stepIndex, item.getAsFile()); showToast(`图片 ${stepIndex + 1} 已粘贴`); state.pasteTarget = null; });
async function runExperiment(index) { const experiment = state.experiments[index]; const card = document.querySelector(`[data-index="${index}"]`); const button = card.querySelector('[data-run]'); button.disabled = true; button.textContent = '运行中…'; try { const response = await fetch('/api/simulate', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ design: experiment.design, testbench: experiment.testbench, designTop: experiment.designTop, simTop: experiment.simTop, duration: '1000ns' }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || `仿真失败（HTTP ${response.status}）`); experiment.result = result; renderExperiments(); renderLatex(); showToast(`实验 ${state.report.number || '1'}-${index + 1} 仿真完成`); } catch (error) { experiment.result = { success: false, log: error.message, tests: [] }; renderExperiments(); renderLatex(); showToast(error.message); } }
function latexTable(result) { const rows = result?.tests || []; const names = Object.keys(rows.find((row) => row.values)?.values || {}); if (!names.length) return '\\textit{未生成测试快照。}\\par\n'; return `\\begin{longtable}{|c|c|${names.map(() => 'c|').join('')}c|}\\hline\n序号 & 时间 & ${names.map(escapeTex).join(' & ')} & 状态 \\\\\n\\hline\\n${rows.map((row, index) => `${index + 1} & ${escapeTex(row.time)} & ${names.map((name) => escapeTex(formatValue(row.values?.[name] ?? '-'))).join(' & ')} & ${row.pass ? 'PASS' : 'INFO'} \\\\\n\\hline`).join('\n')}\n\\end{longtable}\n`; }
function buildLatex() { const r = state.report; let latex = `\\documentclass[UTF8,a4paper,11pt]{ctexart}\n\\usepackage{geometry}\n\\usepackage{graphicx}\n\\usepackage{longtable}\n\\usepackage{float}\n\\usepackage{xcolor}\n\\usepackage{fancyhdr}\n\\geometry{top=2.6cm,bottom=2.4cm,left=2.7cm,right=2.7cm}\n\\definecolor{reportgreen}{HTML}{527D6D}\n\\pagestyle{fancy}\\fancyhf{}\\lhead{\\textcolor{reportgreen}{${escapeTex(r.course || '数字逻辑课程实验')}}}\\rhead{课程实验报告}\\cfoot{\\thepage}\n\\begin{document}\n\\begin{center}\\textcolor{reportgreen}{\\large\\bfseries ${escapeTex(r.course || '数字逻辑课程实验')} }\\par\\vspace{1.2em}{\\LARGE\\bfseries ${escapeTex(r.title || '实验报告')}}\\par\\vspace{1em}\\rule{0.85\\textwidth}{0.5pt}\\end{center}\n\\begin{tabular}{ll}姓名：&${escapeTex(r.name)}\\\\班级：&${escapeTex(r.className)}\\\\学号：&${escapeTex(r.id)}\\\\邮箱：&${escapeTex(r.email)}\\\\实验时间：&${escapeTex(r.date)}\\\\实验环境：&${escapeTex(r.environment)}\\end{tabular}\n\\section{实验目的}\n${escapeTex(r.purpose)}\n\\section{实验原理}\n${escapeTex(r.principle)}\n\\section{实验环境}\n${escapeTex(r.environment)}\n`;
  state.experiments.forEach((experiment, index) => { latex += `\\section{实验 ${index + 1}-${index + 1}：${escapeTex(experiment.title || `实验 1-${index + 1}`)}}\n\\subsection{实验思路}\n${escapeTex(experiment.principle)}\n\\subsection{实验步骤}\n${escapeTex(experiment.steps)}\n\\subsection{Verilog 设计代码}\n\\begin{verbatim}\n${experiment.design}\n\\end{verbatim}\n\\subsection{Testbench 激励代码}\n\\begin{verbatim}\n${experiment.testbench}\n\\end{verbatim}\n\\subsection{仿真结果}\n${latexTable(experiment.result)}\\subsection{实验过程截图}\n`;
    experiment.images.forEach((image, imageIndex) => { if (!image) return; latex += `\\begin{figure}[H]\\centering\\includegraphics[width=0.85\\textwidth]{experiment-${index + 1}-${imageIndex + 1}.png}\\caption{实验 ${state.report.number || '1'}-${index + 1}：${stepLabels[imageIndex]}}\\end{figure}\n`; }); latex += `\\subsection{结果分析}\n${escapeTex(experiment.analysis)}\n`; }); latex += `\\section{问题与分析}\n${escapeTex(r.problems)}\n\\section{实验总结}\n${escapeTex(r.summary)}\n\\section{心得体会}\n${escapeTex(r.reflection)}\n\\end{document}\n`; return latex; }
function renderLatex() { const latex = buildLatex(); $('#latexSource').textContent = latex; $('#reportStats').textContent = `${state.experiments.length} 个子实验`; const r = state.report; $('#latexRender').innerHTML = `<div class="paper"><div class="paper-kicker">${escapeHtml(r.course || '数字逻辑课程实验')}</div><h1>${escapeHtml(r.title || '实验报告')}</h1><div class="paper-rule"></div><dl class="paper-info"><dt>姓名</dt><dd>${escapeHtml(r.name || '未填写')}</dd><dt>班级</dt><dd>${escapeHtml(r.className || '未填写')}</dd><dt>学号</dt><dd>${escapeHtml(r.id || '未填写')}</dd><dt>实验环境</dt><dd>${escapeHtml(r.environment || '未填写')}</dd></dl><h2>一、实验目的</h2><p>${escapeHtml(r.purpose || '尚未填写')}</p><h2>二、实验原理</h2><p>${escapeHtml(r.principle || '尚未填写')}</p><h2>三、实验内容与结果</h2>${state.experiments.map((experiment, index) => `<h3>实验 1-${index + 1}：${escapeHtml(experiment.title || `实验 1-${index + 1}`)}</h3><p>${escapeHtml(experiment.principle || '尚未填写实验思路')}</p>${experiment.result ? `<p class="result-ok">仿真状态：${experiment.result.success ? 'PASS' : 'FAIL'} · ${experiment.result.tests?.length || 0} 条测试记录</p>` : '<p>尚未运行仿真</p>'}${experiment.images.length ? `<div class="preview-images">${experiment.images.map((image) => `<img src="${image.data}" alt="过程截图">`).join('')}</div>` : ''}`).join('')}<h2>四、问题与分析</h2><p>${escapeHtml(r.problems || '尚未填写')}</p><h2>五、实验总结</h2><p>${escapeHtml(r.summary || '尚未填写')}</p><h2>六、心得体会</h2><p>${escapeHtml(r.reflection || '尚未填写')}</p></div>`; }
function bindReportEvents() { document.querySelectorAll('#reportWorkspace input, #reportWorkspace textarea').forEach((field) => field.addEventListener('input', updateReportState)); }
$('#addExperiment').addEventListener('click', () => { const experiment = newExperiment(); experiment.title = `实验 ${state.report.number || '1'}-${state.experiments.length + 1}`; state.experiments.push(experiment); renderExperiments(); renderLatex(); });
$('#radixSelect')?.addEventListener('change', (event) => { state.radix = event.target.value; renderExperiments(); renderLatex(); });
$('#copyLatex').addEventListener('click', async () => { try { await navigator.clipboard.writeText($('#latexSource').textContent); showToast('LaTeX 已复制'); } catch { showToast('复制失败，请切换到源码后手动复制'); } });
$('#downloadLatex').addEventListener('click', () => { const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([$('#latexSource').textContent], { type: 'application/x-tex;charset=utf-8' })); link.download = 'experiment-report.tex'; link.click(); showToast('LaTeX 文件已导出'); });
$('#sourceTab').addEventListener('click', () => { $('#latexSource').style.display = 'block'; $('#latexRender').style.display = 'none'; $('#sourceTab').classList.add('active'); $('#renderTab').classList.remove('active'); });
$('#renderTab').addEventListener('click', () => { $('#latexSource').style.display = 'none'; $('#latexRender').style.display = 'block'; $('#renderTab').classList.add('active'); $('#sourceTab').classList.remove('active'); });
$('#quickMode').addEventListener('click', () => { $('#reportWorkspace').classList.add('hidden'); $('#quickWorkspace').classList.remove('hidden'); $('#quickMode').classList.add('active'); $('#reportMode').classList.remove('active'); });
$('#reportMode').addEventListener('click', () => { $('#quickWorkspace').classList.add('hidden'); $('#reportWorkspace').classList.remove('hidden'); $('#reportMode').classList.add('active'); $('#quickMode').classList.remove('active'); });
state.experiments.push(Object.assign(newExperiment(), { title: '实验 1-1', design: exampleDesign, testbench: exampleTb, designTop: 'counter', simTop: 'counter_tb' })); bindReportEvents(); renderExperiments(); updateReportState();
